## Numpy

Help in faster calculation and math operations over entire array.

In [1]:
import numpy as np

## Numpy Array

Array can contain only simple datatype and can perform calculation over the entire array unlike python list

In [2]:
np_array = np.array([2,3,4,5,8])

In [3]:
np_array > 6

array([False, False, False, False,  True])

In [4]:
np_array[np_array>6]

array([8])

## N-Dimensional Array

In [27]:
np_2d_array = np.array([[2,3,4,5,1], [14,4,5,4,2]])

In [28]:
np_3d_array = np.array([[[2,3,4,5], [2,2,4,5]], [[2,2,1,1], [2,2,3,1]]])

In [29]:
np_3d_array.shape

(2, 2, 4)

## Indexing

In [33]:
np_2d_array[1,2]

5

In [35]:
np_3d_array[1,0,1]

2

### Negative Indexing


In [36]:
np_3d_array[1,0,-1]

1

## Array Slicing

In [38]:
np_2d_array[0:, 2]

array([4, 5])

## Data Type

- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

In [39]:
np_2d_array.dtype

dtype('int64')

In [42]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
arr.dtype

[b'1' b'2' b'3' b'4']


dtype('S1')

## Copy vs View

In [43]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## Generate data


In [18]:
height = np.round(np.random.normal(1.75, 0.2, 5000), 2)
weight = np.round(np.random.normal(62, 15, 5000), 2)

In [19]:
height

array([1.84, 1.85, 1.44, ..., 1.54, 1.62, 1.49])

In [20]:
np_city = np.column_stack((height, weight))

In [21]:
np_city

array([[  1.84, 117.34],
       [  1.85,  61.5 ],
       [  1.44,  73.01],
       ...,
       [  1.54,  62.97],
       [  1.62,  47.96],
       [  1.49,  54.7 ]])

## Shape of array

In [44]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


## Arrary Splitter

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [47]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


## Searching Arrays

In [48]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


`searchsorted()` which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order and it assume to be used on sorted arrays.

In [50]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 10)
print(x)

4


## Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

In [51]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [52]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Filtering Arrays

Getting some elements out of an existing array and creating a new array out of them is called filtering.